config/routes.rb
Rails.application.routes.draw do  
  resources :tv_shows, only: :index do
  	get :favourite, on: :member
  end
  
  get :favourites, to: 'users#favourites'

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :tv_shows
end

app/models/favourite.rb
class Favourite < ApplicationRecord
	belongs_to :user
  belongs_to :tv_show
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
	belongs_to :channel
  has_many :favourites
  has_many :users, through: :favourites

	def start_time
    time_strf(read_attribute(:start_time)) if read_attribute(:start_time).present?
  end

  def start_time=(value)
    write_attribute(:start_time, Time.parse(value).seconds_since_midnight) if value.present?
  end

  def end_time
    time_strf(read_attribute(:end_time)) if read_attribute(:end_time).present?
  end

  def end_time=(value)
    write_attribute(:end_time, Time.parse(value).seconds_since_midnight) if value.present?
  end

  def time_strf(time_digit)
    (Time.now.at_midnight + time_digit).strftime("%H:%M")
  end

  def self.required_data(query)
    TvShow.joins(:channel).select('tv_shows.*, channels.name as channel_name').where("channels.name LIKE '%#{query}%' OR tv_shows.name LIKE '%#{query}%'")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites
  has_many :tv_shows, through: :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :find_tv_show, only: :favourite

  def index
  	@tv_shows = TvShow.required_data(params[:q])
  end

  def favourite
  	fav = Favourite.new(user_id: current_user.id, tv_show_id: @tv_show.id)
  	if fav.save
  		flash[:success] = 'Successfully marked as favourite'
  	else
      flash[:notice] = 'Could not marked as favourite'
  	end
  	redirect_to tv_shows_path
  end

  private

  def find_tv_show
  	@tv_show = TvShow.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def favourites
		@favourites = current_user.tv_shows
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/tv_shows">PVR App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/favourites">My Favourites <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <%= form_with(url: "/tv_shows", method: "get", html: { class: 'form-inline my-2 my-lg-0' }) do %>
      <%= label_tag(:q, "Search ") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTechment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if user_signed_in? %>
        <%= render partial: "layouts/header" %>
      <% end %>
      <div class="content-wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tv_shows/_tv_shows.html.erb
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Channel Name</th>
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
    <th scope="col">Mark Favourite</th>
  </tr>
</thead>
<tbody>
  <% @tv_shows.each_with_index do |tv_show, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= tv_show.name %></td>
      <td><%= tv_show.channel_name %></td>
      <td><%= tv_show.start_time %></td>
      <td><%= tv_show.end_time %></td>
      <td><%= link_to "Favourite", favourite_tv_show_path(tv_show.id) %></td>
    <tr>
  <% end %>
</tbody>

app/views/tv_shows/index.html.erb
<br>
<h3>Tv Shows</h3>
<br>

<table class="table" id="tv-shows">
  <%= render "tv_shows" %>
</table>

app/views/tv_shows/index.js.erb
$('#tv-shows').html("<%= j render(:partial => 'tv_shows') %>");

app/views/users/favourites.html.erb
<br>
<h3>My Favourite</h3>
<br>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
  </tr>
</thead>

<tbody>
  <% @favourites.each_with_index do |favourite, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= favourite.name %></td>
      <td><%= favourite.start_time %></td>
      <td><%= favourite.end_time %></td>
    <tr>
  <% end %>
</tbody>
</table>